{{- range list "storefront" "admin" }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ . }}
  namespace: {{ $.Values.global.namespace }}
  labels:
    app: {{ . }}
    {{- include "retail.labels" $ | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ . }}
  template:
    metadata:
      labels:
        app: {{ . }}
        {{- include "retail.labels" $ | nindent 8 }}
    spec:
      serviceAccountName: {{ $.Values.global.serviceAccount.name }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 101
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: {{ . }}
          image: "{{ $.Values.global.imageRegistry }}/{{ . }}:{{ $.Values.global.imageTag }}"
          imagePullPolicy: {{ $.Values.global.imagePullPolicy }}
          ports:
            - name: http
              containerPort: 8080
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop: ["ALL"]
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 3
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            {{- toYaml $.Values.global.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ . }}
  namespace: {{ $.Values.global.namespace }}
  labels:
    app: {{ . }}
    {{- include "retail.labels" $ | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: {{ . }}
  ports:
    - port: 80
      targetPort: http
      name: http
{{- end }}
