{{- if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: retail-external-gateway
  namespace: {{ .Values.global.namespace }}
  annotations:
    networking.gke.io/certmap: retail-cert-map
spec:
  gatewayClassName: gke-l7-global-external-managed
  listeners:
    - name: https
      protocol: HTTPS
      port: 443
      hostname: {{ .Values.gateway.hostname }}
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: retail-tls
    - name: https-admin
      protocol: HTTPS
      port: 443
      hostname: {{ .Values.gateway.adminHostname }}
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: retail-admin-tls
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: retail-bff-route
  namespace: {{ .Values.global.namespace }}
spec:
  parentRefs:
    - name: retail-external-gateway
      sectionName: https
  hostnames:
    - {{ .Values.gateway.hostname }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /api
      backendRefs:
        - name: bff-api-service
          port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: retail-admin-route
  namespace: {{ .Values.global.namespace }}
spec:
  parentRefs:
    - name: retail-external-gateway
      sectionName: https-admin
  hostnames:
    - {{ .Values.gateway.adminHostname }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: bff-api-service
          port: 80
{{- end }}
