{{- if .Values.global.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress
  namespace: {{ .Values.global.namespace }}
spec:
  podSelector: {}
  policyTypes: ["Ingress"]
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-gateway-to-bff
  namespace: {{ .Values.global.namespace }}
spec:
  podSelector:
    matchLabels:
      app: bff-api-service
  policyTypes: ["Ingress"]
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: gateway-system
      ports:
        - protocol: TCP
          port: 8080
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-bff-to-domain-services
  namespace: {{ .Values.global.namespace }}
spec:
  podSelector:
    matchExpressions:
      - key: domain
        operator: Exists
  policyTypes: ["Ingress"]
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: bff-api-service
      ports:
        - protocol: TCP
          port: 8080
    - from:
        - podSelector:
            matchExpressions:
              - key: domain
                operator: In
                values:
                  - commerce
                  - catalog
                  - identity
      ports:
        - protocol: TCP
          port: 8080
{{- end }}
